# Generated by Django 3.1.1 on 2020-12-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=70)),
                ('student_email', models.EmailField(max_length=100)),
                ('student_roll', models.IntegerField()),
            ],
        ),
    ]
