# Generated by Django 3.1.1 on 2021-01-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0002_auto_20210104_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password2',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
